config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, controllers: { registrations: 'authors/registrations' }

  root 'posts#index'

  get 'posts' => 'posts#index'
  get 'posts/current/author' => 'posts#author_posts'

  namespace :api do
    scope '1.0' do
      resources :posts, only: [:create]
      resources :comments, only: [:create]
      resources :replies, only: [:create]
    end
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts

   validates_presence_of :first_name
   validates_presence_of :last_name
   validates_presence_of :gender
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :replies
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author

  has_many :comments
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController

  before_filter :authenticate_author!

  def create
    comment = Comment.new(comment_params)
    if comment.save
      status = 1
    else
      status = 0
    end
    render json: { status: status, comment: comment }
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :name, :content).merge(author_id: current_author.id)
  end

end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  before_filter :authenticate_author!

  def create
    post = Post.new(post_params)
    if post.save
  
      post_return = {
        id: post.id,
        name: post.name,
        content: post.content,
        created_at: post.created_at,
        first_name: post.author.first_name,
        last_name: post.author.last_name,
      }

      status = 1
    else
      status = 0
    end
    render json: { status: status, post: post_return }
  end

  private

  def post_params
    params.require(:post).permit(:name, :content).merge(author_id: current_author.id)
  end

end

app/controllers/api/replies_controller.rb
class Api::RepliesController < ApplicationController

  before_filter :authenticate_author!

  def create
    reply = Reply.new(reply_params)
    if reply.save
      status = 1
    else
      status = 0
    end
    render json: { status: status, reply: reply }
  end

  private

  def reply_params
    params.require(:reply).permit(:comment_id, :name, :content).merge(author_id: current_author.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/authors/registrations_controller.rb
class Authors::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at desc")
  end

  def author_posts
    @posts = false
    if author_signed_in?
      @posts = current_author.posts.order("created_at desc")
    end
  end

end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/api/replies_helper.rb
module Api::RepliesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorPosts</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <a href="<%= url_for root_path %>">Home</a>
    <% if author_signed_in? %>
      &nbsp;|&nbsp;
      <a href="<%= url_for controller: "posts", action: "author_posts" %>">My Posts</a>
      &nbsp;|&nbsp;
      <%= link_to "Logout", destroy_author_session_path, method: :delete  %>
      &nbsp;|&nbsp;
      Welcome <%= current_author.first_name %>!
    <% else %>
      &nbsp;|&nbsp;
      <a href="<%= url_for new_author_session_path %>">Login</a>
      or
      <a href="<%= url_for new_author_registration_path %>">Register</a>
    <% end %>
    <hr />

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<ul id="form-errors" style="display: none;" class="error-list"></ul>
<form action="<%= url_for(controller: "/api/posts", action: 'create') %>" id="post-form" redirect_url="<%= url_for(action: 'index') %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <table>
    <tr>
      <td>Post name:</td>
      <td><input type="text" name="name" /></td>
    </tr>
    <tr>
      <td>Content:</td>
      <td><textarea name="content"></textarea></td>
    </tr>
  </table>
  <a href="<%= url_for action: "index" %>">Cancel</a>
  &nbsp;
  <button type="submit">Save</button>
</form>

app/views/posts/author_posts.html.erb
<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>  
  </div>
<% end %>

<center>

  <div class="new-post">
    <ul id="form-errors" style="display: none;" class="error-list"></ul>
    <form action="<%= url_for(controller: "/api/posts", action: 'create') %>" id="post-form" redirect_url="<%= url_for(action: 'index') %>">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <table>
        <tr>
          <td>Post name:</td>
          <td><input type="text" name="name" /></td>
        </tr>
        <tr>
          <td>Content:</td>
          <td><textarea name="content"></textarea></td>
        </tr>
      </table>
      <button type="submit">Submit Post</button>
    </form>
  </div>

  <div id="post-loader" style="display: none;">Loading....</div>

  <div id="post-list">
    <% if @posts %>
      <% @posts.each do |post| %>
        <div class="post">
          <h3><%= post.name %></h3>
          <p><%= post.content %></p>
          <span class="timestamp">By: <%= post.author.email %></span>
          <span class="timestamp">Created: Apr 13, 2017</span>

          <div class="comment-form">
            <form action="" class="new-comment">
              <h4>New Comment</h4>
              <input type="hidden" name="post_id" value="<%= post.id %>">
              <textarea name="content"></textarea>
              <br />
              <button>Submit</button>
            </form>
          </div>

          <div class="comments-list">
            <h4 class="title" style="<%= post.comments.count == 0 ? "display: none;" : ""%>"">Comments</h4>
            <ul class="all-comments">
              <% if post.comments.count > 0 %>
                <% post.comments.each do |comment| %> 
                  <li>
                    <%= comment.content %>
                    &nbsp;&nbsp;&nbsp;
                    <a href="" class="reply-link">Reply</a>
                    <form action="" class="reply-form">
                      <input type="hidden" name="comment_id" value="<%= comment.id %>">
                      <textarea name="content"></textarea>
                      <br />
                      <button>Submit</button>
                      &nbsp;|&nbsp;
                      <a href="" class="cancel-link">Cancel</a>
                    </form>
                    <ul class="sub-comments">
                      <% if comment.replies %>
                        <% comment.replies.each do |reply| %>
                          <li><%= reply.content %></li>
                        <% end %>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</center>

app/views/posts/edit.html.erb
<h3><%= @title %></h3>

<%= render :partial => 'form', locals: { user: @user }  %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>  
  </div>
<% end %>

<center>

  <% if author_signed_in? %>
    <div class="new-post">
      <ul id="form-errors" style="display: none;" class="error-list"></ul>
      <form action="<%= url_for(controller: "/api/posts", action: 'create') %>" id="post-form" redirect_url="<%= url_for(action: 'index') %>">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <table>
          <tr>
            <td>Post name:</td>
            <td><input type="text" name="name" /></td>
          </tr>
          <tr>
            <td>Content:</td>
            <td><textarea name="content"></textarea></td>
          </tr>
        </table>
        <button type="submit">Submit Post</button>
      </form>
    </div>

    <div id="post-loader" style="display: none;">Loading....</div>
  <% end %>

  <div id="post-list">
    <% if @posts %>
      <% @posts.each do |post| %>
        <div class="post">
          <h3><%= post.name %></h3>
          <p><%= post.content %></p>
          <span class="timestamp">By: <%= post.author.first_name %> <%= post.author.last_name %></span>
          <span class="timestamp">Created: Apr 13, 2017</span>

          <div class="comment-form">
            <form action="" class="new-comment">
              <h4>New Comment</h4>
              <input type="hidden" name="post_id" value="<%= post.id %>">
              <textarea name="content"></textarea>
              <br />
              <button>Submit</button>
            </form>
          </div>

          <div class="comments-list">
            <h4 class="title" style="<%= post.comments.count == 0 ? "display: none;" : ""%>"">Comments</h4>
            <ul class="all-comments">
              <% if post.comments.count > 0 %>
                <% post.comments.each do |comment| %> 
                  <li>
                    <%= comment.content %>
                    <div class="comment-info">
                      <i>By: <%= comment %></i>
                      -
                      <a href="" class="reply-link">Reply</a>
                    </div>
                    <form action="" class="reply-form">
                      <input type="hidden" name="comment_id" value="<%= comment.id %>">
                      <textarea name="content"></textarea>
                      <br />
                      <button>Submit</button>
                      &nbsp;|&nbsp;
                      <a href="" class="cancel-link">Cancel</a>
                    </form>
                    <ul class="sub-comments">
                      <% if comment.replies %>
                        <% comment.replies.each do |reply| %>
                          <li>
                            <%= reply.content %>
                            <div class="comment-info">
                              <i>By: <%#= comment %></i>
                            </div>
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</center>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render :partial => 'form'  %>